name: CI-pt5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      # 3. Install dependencies
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      # 4. Run RSpec tests
      - name: Run RSpec tests
        run: bundle exec rspec --format documentation

      # 5. Setup RuboCop config to auto-enable new cops
      - name: Setup RuboCop config
        run: |
          cat <<EOF > .rubocop.yml
AllCops:
  NewCops: enable
EOF

      # 6. Run RuboCop lint
      - name: Run RuboCop lint
        run: bundle exec rubocop --display-cop-names --extra-details --display-style-guide
